# Generated by Django 3.0.4 on 2020-04-08 18:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('image', models.URLField(max_length=255, verbose_name='Type image')),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True, verbose_name='Active Category?')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Category Creation Date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='author Alias')),
                ('contribution', models.IntegerField(default=0, verbose_name='author Contribution')),
                ('status', models.BooleanField(default=True, verbose_name='Active author?')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='author Creation Date')),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag')),
                ('image', models.URLField(max_length=300, verbose_name='Type image')),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True, verbose_name='Active Tag?')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Tag creation Date')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type')),
                ('image', models.URLField(max_length=300, verbose_name='Type image')),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True, verbose_name='Active Type?')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Type creation date')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Suggestion Title')),
                ('slug', models.SlugField()),
                ('image', models.URLField(max_length=300, verbose_name='Suggestion Image')),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Suggestion creation date')),
                ('ranking', models.IntegerField(default=0, verbose_name='Suggestion Ranking')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile')),
                ('tag', models.ManyToManyField(to='blog.Tag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Type')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
            },
        ),
    ]
