# Generated by Django 3.0.4 on 2020-04-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alias',
            new_name='first_name',
        ),
    ]
