# Generated by Django 3.0.4 on 2020-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='author Alias'),
        ),
    ]
