# Generated by Django 3.0.4 on 2020-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200408_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(max_length=100, verbose_name='author Alias'),
        ),
    ]
