# Generated by Django 3.0.4 on 2020-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200412_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Suggestion Votes Ranking'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Suggestion Views Ranking'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='slug',
            field=models.SlugField(default='asd'),
        ),
    ]
