# Generated by Django 3.0.4 on 2020-04-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='blog.Tag'),
        ),
    ]
